###login admin

POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "dostonbek",
  "password": "1234"
}





###create admin

POST http://localhost:5000/admins
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzI0NTE1Mjg5ZDM5YTgwZGQ2OTczNCIsImlzU3VwZXIiOnRydWUsImlhdCI6MTY5MDU1OTg2MCwiZXhwIjoxNjkwNjQ2MjYwfQ.yL4whOaI2947tSwkQY0tqtlomjovBrpnDosZ3CvqhiE

{
  "full_name": "Jurayev Doston",  
  "username": "dostonbek",
  "password": "1234"
}




###get admins

GET http://localhost:5000/admins
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzI0NTE1Mjg5ZDM5YTgwZGQ2OTczNCIsImlzU3VwZXIiOnRydWUsImlhdCI6MTY5MDU1OTg2MCwiZXhwIjoxNjkwNjQ2MjYwfQ.yL4whOaI2947tSwkQY0tqtlomjovBrpnDosZ3CvqhiE
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzI1MTJkN2FhNWYxY2QyYWI2N2FjYiIsImlzU3VwZXIiOmZhbHNlLCJpYXQiOjE2OTA1NjAyNDgsImV4cCI6MTY5MDY0NjY0OH0.WRXhNLml2FQmMs-Zh3lyY2cx9JZY3AUyRFaxp2nFiQE



###show admins

GET http://localhost:5000/admins/64c24515289d39a80dd69734
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzI0NTE1Mjg5ZDM5YTgwZGQ2OTczNCIsImlzU3VwZXIiOnRydWUsImlhdCI6MTY5MDU1OTg2MCwiZXhwIjoxNjkwNjQ2MjYwfQ.yL4whOaI2947tSwkQY0tqtlomjovBrpnDosZ3CvqhiE

