###login admin

POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "sherozbek.17",
  "password": "1234"
}





###create admin

POST http://localhost:5000/admins
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzUxZWVmODFhYWJhNzQ0ZDU3NDU3ZiIsImlzU3VwZXIiOnRydWUsImlhdCI6MTY5MTA1Mjk0MSwiZXhwIjoxNjkxMTM5MzQxfQ.frWpt4_tJk6b7jdTGoM-qy6Vad-e6wAXTpnDSLVlIeQ

{
  "full_name": "Jurayev Doston",  
  "username": "dostonbek",
  "password": "1234"
}




###get admins

GET http://localhost:5000/admins
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzUxZWVmODFhYWJhNzQ0ZDU3NDU3ZiIsImlzU3VwZXIiOnRydWUsImlhdCI6MTY5MTA1MDM5MSwiZXhwIjoxNjkxMTM2NzkxfQ.86z3qCy_pTNRFV9UkEBWUDTsZyS9pqPSkzU6OmCRrr8




###show admins

GET http://localhost:5000/admins/64c51eef81aaba74d57457f
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzUxZWVmODFhYWJhNzQ0ZDU3NDU3ZiIsImlzU3VwZXIiOnRydWUsImlhdCI6MTY5MTA1MDM0NCwiZXhwIjoxNjkxMTM2NzQ0fQ.95a8c-_XTsbyd8s_e89xS-tFT37azgEs9Ry2LvZlmws


###patch admins

PATCH  http://localhost:5000/admins/me
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzI0NTE1Mjg5ZDM5YTgwZGQ2OTczNCIsImlzU3VwZXIiOnRydWUsImlhdCI6MTY5MDU1OTg2MCwiZXhwIjoxNjkwNjQ2MjYwfQ.yL4whOaI2947tSwkQY0tqtlomjovBrpnDosZ3CvqhiE

{
  "username": "sherozbek.17",
  "password": "1234",
  "full_name": "Koko Joej"
}



### admins

DELETE  http://localhost:5000/admins/64c51eef81aaba744d57457f
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzUxZWVmODFhYWJhNzQ0ZDU3NDU3ZiIsImlzU3VwZXIiOnRydWUsImlhdCI6MTY5MTA1MDM5MSwiZXhwIjoxNjkxMTM2NzkxfQ.86z3qCy_pTNRFV9UkEBWUDTsZyS9pqPSkzU6OmCRrr8






###
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzI1MTJkN2FhNWYxY2QyYWI2N2FjYiIsImlzU3VwZXIiOmZhbHNlLCJpYXQiOjE2OTA1NjAyNDgsImV4cCI6MTY5MDY0NjY0OH0.WRXhNLml2FQmMs-Zh3lyY2cx9JZY3AUyRFaxp2nFiQE
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzI0NTE1Mjg5ZDM5YTgwZGQ2OTczNCIsImlzU3VwZXIiOnRydWUsImlhdCI6MTY5MDU1OTg2MCwiZXhwIjoxNjkwNjQ2MjYwfQ.yL4whOaI2947tSwkQY0tqtlomjovBrpnDosZ3CvqhiE