### CREATE BORROWERS
POST http://localhost:5000/borrowers
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzUxZWVmODFhYWJhNzQ0ZDU3NDU3ZiIsImlzU3VwZXIiOnRydWUsImlhdCI6MTY5MTA2NjE4NSwiZXhwIjoxNjkxMTUyNTg1fQ.AgCQr3f5z2LMkYzTLAghiKhS8KeR8iikV_-Xc3smdQc

{
  "full_name": "Xurshidbek Komilov",
  "address": "Jizzax",
  "phone": "+998943435633"
}


### GET BORROWERS
GET http://localhost:5000/borrowers
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzUxZWVmODFhYWJhNzQ0ZDU3NDU3ZiIsImlzU3VwZXIiOnRydWUsImlhdCI6MTY5MTA2NjE4NSwiZXhwIjoxNjkxMTUyNTg1fQ.AgCQr3f5z2LMkYzTLAghiKhS8KeR8iikV_-Xc3smdQc


### GET ONEBORROWERS
GET http://localhost:5000/borrowers/64c41084a98be9bd61ecc285
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzUxZWVmODFhYWJhNzQ0ZDU3NDU3ZiIsImlzU3VwZXIiOnRydWUsImlhdCI6MTY5MTA2NjE4NSwiZXhwIjoxNjkxMTUyNTg1fQ.AgCQr3f5z2LMkYzTLAghiKhS8KeR8iikV_-Xc3smdQc


### EDIT BORROWERS
PATCH http://localhost:5000/borrowers/64c51fe58241d6d400dfb012
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzUxZWVmODFhYWJhNzQ0ZDU3NDU3ZiIsImlzU3VwZXIiOnRydWUsImlhdCI6MTY5MTA2NjE4NSwiZXhwIjoxNjkxMTUyNTg1fQ.AgCQr3f5z2LMkYzTLAghiKhS8KeR8iikV_-Xc3smdQc

{
  "full_name": "raimov jaxongir",
  "address": "Sufi Guzar",
  "phone": "+998968564525"
}


### DELETE BORROWERS
DELETE http://localhost:5000/borrowers/64c41084a98be9bd61ecc285
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzUxZWVmODFhYWJhNzQ0ZDU3NDU3ZiIsImlzU3VwZXIiOnRydWUsImlhdCI6MTY5MTA2NjE4NSwiZXhwIjoxNjkxMTUyNTg1fQ.AgCQr3f5z2LMkYzTLAghiKhS8KeR8iikV_-Xc3smdQc