### CREATE PUBLISHER
POST http://localhost:5000/publisher
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzUxZWVmODFhYWJhNzQ0ZDU3NDU3ZiIsImlzU3VwZXIiOnRydWUsImlhdCI6MTY5MTA2MDYyOSwiZXhwIjoxNjkxMTQ3MDI5fQ.5-p2TB6r2vQITcVfCIYaCdvaGcOdaT9PJ_NlId3WJuE

{
  "full_name": "Inson - nashriyot",
  "address": "Toshkent",
  "phone": "+998771118811"
}


### GET PUBLISHER
GET http://localhost:5000/publisher
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzUxZWVmODFhYWJhNzQ0ZDU3NDU3ZiIsImlzU3VwZXIiOnRydWUsImlhdCI6MTY5MTA2MDYyOSwiZXhwIjoxNjkxMTQ3MDI5fQ.5-p2TB6r2vQITcVfCIYaCdvaGcOdaT9PJ_NlId3WJuE

### GET PUBLISHER ?q=Palon
GET http://localhost:5000/publisher?q=f
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzUxZWVmODFhYWJhNzQ0ZDU3NDU3ZiIsImlzU3VwZXIiOnRydWUsImlhdCI6MTY5MTA2MDYyOSwiZXhwIjoxNjkxMTQ3MDI5fQ.5-p2TB6r2vQITcVfCIYaCdvaGcOdaT9PJ_NlId3WJuE

### GET PUBLISHER ?sort[by]=palon&sort[order]=desc
GET http://localhost:5000/publisher?sort[by]=full_name&sort[order]=desc
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzUxZWVmODFhYWJhNzQ0ZDU3NDU3ZiIsImlzU3VwZXIiOnRydWUsImlhdCI6MTY5MTA2MDYyOSwiZXhwIjoxNjkxMTQ3MDI5fQ.5-p2TB6r2vQITcVfCIYaCdvaGcOdaT9PJ_NlId3WJuE


### GET ONE PUBLISHER
GET http://localhost:5000/publisher/64c520408241d6d400dfb015
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzUxZWVmODFhYWJhNzQ0ZDU3NDU3ZiIsImlzU3VwZXIiOnRydWUsImlhdCI6MTY5MTA2MDYyOSwiZXhwIjoxNjkxMTQ3MDI5fQ.5-p2TB6r2vQITcVfCIYaCdvaGcOdaT9PJ_NlId3WJuE


### EDIT PUBLISHER
PATCH http://localhost:5000/publisher/64c520198241d6d400dfb013
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzUxZWVmODFhYWJhNzQ0ZDU3NDU3ZiIsImlzU3VwZXIiOnRydWUsImlhdCI6MTY5MTA2MDYyOSwiZXhwIjoxNjkxMTQ3MDI5fQ.5-p2TB6r2vQITcVfCIYaCdvaGcOdaT9PJ_NlId3WJuE

{
  "full_name": "Inson - nashriyot",
  "address": "Toshkent",
  "phone": "+998771118811"
}


### DELETE PUBLISHER
DELETE http://localhost:5000/publisher/64c4236dd5b26a8e64c32393
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzUxZWVmODFhYWJhNzQ0ZDU3NDU3ZiIsImlzU3VwZXIiOnRydWUsImlhdCI6MTY5MTA2MDYyOSwiZXhwIjoxNjkxMTQ3MDI5fQ.5-p2TB6r2vQITcVfCIYaCdvaGcOdaT9PJ_NlId3WJuE



